# Generated by Django 5.1.6 on 2025-05-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_prod',
            field=models.BooleanField(default=False),
        ),
    ]
