# Generated by Django 5.1.6 on 2025-05-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_product_new_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dotd',
            field=models.BooleanField(default=False),
        ),
    ]
