# Generated by Django 5.1.6 on 2025-05-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_product_secondary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_sellers',
            field=models.BooleanField(default=False),
        ),
    ]
