# Generated by Django 5.1.6 on 2025-05-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_product_best_sellers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=False, null=False,  unique=True, max_length=50),
        ),
    ]
