# Generated by Django 5.1.6 on 2025-05-28 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_subcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
    ]
