# Generated by Django 5.1.6 on 2025-06-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_add_initial_categories'),
        ('home', '0026_remove_order_items_orderitem'),
    ]

    operations = [
    ]
