# Generated by Django 5.1.6 on 2025-06-10 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_migrate_images_to_cloudinary'),
        ('home', '0028_add_nav_categories'),
    ]

    operations = [
    ]
